gruppen:
  organisator: cnlutong
  tutor: cnlutong


spring:
  flyway:
    schemas: student
    create-schemas: true
    url: jdbc:mariadb://localhost:3310/
    user: root
    password: iamgroot
  datasource:
    url: jdbc:mariadb://localhost:3310/student
    username: root
    password: iamgroot

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: user

        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token

