spring:
  flyway:
    schemas: chicken
    create-schemas: true
    url: jdbc:mariadb://localhost:3310/
    user: root
    password: iamgroot
  datasource:
    url: jdbc:mariadb://localhost:3310/chicken
    username: root
    password: iamgroot
